language: python
sudo: false

before_install:
  - pip install codecov

install:
  - pip install tox

script:
  - tox

matrix:
  fast_finish: true

  include:
    # Python 3.5
    - python: 3.5
      env: TOXENV=py35-django111

    # Python 3.6
    - python: 3.6
      env: TOXENV=py36-django111

after_success:
  - codecov
